# Generated by Django 2.2 on 2019-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='titleid',
            field=models.IntegerField(default=None),
        ),
    ]
