# Generated by Django 2.2 on 2019-04-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190410_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='titleid',
        ),
    ]
