# Generated by Django 2.2 on 2019-04-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20190410_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='title',
        ),
    ]
