# Generated by Django 2.2 on 2019-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_moviereview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
